### ISSUE TITLE
How to Change Color of Components

### ISSUE THREAD

**Issue by Balwant-Singh-Rathore** [LiveDuo/destack#105]
Hey, Great Project Thanks for this
I have one question how can we change the color of a component from builder-like
I want to change the colour of buttons using the colour picker form builder and save it so it's possible.
It's also fine if we change colour from available Tailwind CSS classes by replacing class so how can we do it?

**Comment by LiveDuo** [comment]
@Balwant-Singh-Rathore @gustavo-camello @bokolob It's now possible with v3. You can use the DevTools to edit the component CSS or change it's tailwind classes.

**Comment by Balwant-Singh-Rathore** [comment]
> @Balwant-Singh-Rathore @gustavo-camello @bokolob It's now possible with v3. You can use the DevTools to edit the component CSS or change it's tailwind classes.

can you explain how can we change as of now i have install v3 but not get any option to update colors and classes

**Comment by LiveDuo** [comment]
Just use your browser DevTools as normal. Changes are automatically saved across page refresh.

https://github.com/LiveDuo/destack/assets/370612/430540a1-b65d-4be6-8091-fae88d14a41a
