### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by vispamir** [LiveDuo/destack#106]
1.  Add option for enable right-to-left layout
2. Create rtl version for all ready elements in Destack

**Comment by LiveDuo** [comment]
@vispamir Destack v3 has just been released and supports editing the HTML. You can use [dir](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#dir) to align your content to the right.

About (2), I don't think I'd ever have the capacity of recreating all components for RTL (there hundreds of then) so I wouldn't have any hope for that one.
