### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by rmasonhx12** [LiveDuo/destack#114]
I opened up the project and while project work -- css is locked and can't expand to larger size or adjust -- looking at document all I seem to be able to find does not give me control over the css -- could you kindly point me to this

**Comment by LiveDuo** [comment]
@rmasonhx12 you can now edit the CSS properties or the tailwind classes with the latest release (v3). When you setup it up either edit the CSS in the DevTools or edit the template file directly which now uses HTML.
