### ISSUE TITLE
destack crashes and needs manual restart

### ISSUE THREAD

**Issue by ezekiel747** [LiveDuo/destack#121]
Hello, i've noticed some issues with destack. Here are the steps:
1. get destack running locally and open the app in browser (i've used destack-react-starter)
2. having the HyperUI theme selected (default), expand the Banner category
3. try to select Tailblocks theme (or other theme which lacks Banner category)

At this point i would expect the theme to change, the categories in the left side to update, and allow me to continue working.
Instead, the UI becomes unusable, the script crashes trying to get some images from the wrong path.

suggested solutions: 
- script should not crash when target file not found. Instead, maybe try-catch and respond with a 404 status.
- UI should not break if a request to backend fails. Instead, display an error (toast notif / alert / something similar) and advise the user to retry.

Thank you in advance for looking into this.
Great work btw! I like the variety of components available.

**Comment by LiveDuo** [comment]
Hey @ezekiel747, thanks for the submission.

Just got the time to look into it and pushed a fix https://github.com/LiveDuo/destack/commit/13bbb7226a1e7bcd2ee3b4cbe12bdd792f7056a1.

Get the latest version with:
```sh
npm i destack@latest
```

If you still experience issues, LMK

**Comment by ezekiel747** [comment]
I've tested the new version, it works fine now.
Thank you!
