### ISSUE TITLE
Would you mind migrating this project to Typescript?

### ISSUE THREAD

**Issue by JcdeA** [LiveDuo/destack#2]
Title. 

For now, Javascript might be feasible, but as the project grows, Typescript will certainly help reduce bugs. I am willing to type the whole project (for fun) If you mind..

Btw, I was the one on reddit that commented [this](https://www.reddit.com/r/nextjs/comments/njgg24/i_created_a_landing_page_builder_for_nextjs_works/gz92rk9?utm_source=share&utm_medium=web2x&context=3)

**Comment by LiveDuo** [comment]
That's very true. Feel free to work on the typescript definitions for the project. I will take a close look when their ready to deal with any potential issues and get them merged.

As a side note, it would be great if we can reduce the friction to contribute to the project. At the moment to set it up you have to do a bit of a trickery to sort out dependencies ([contributing-to-the-project](https://github.com/LiveDuo/destack#contributing-to-the-project)). That should be simplified vastly by correctly setting up react as peerDependency and grapesjs as dependency. I'm looking at it right now and any help is much appriciated.

**Comment by JcdeA** [comment]
Thanks for the support!

I've read through the source and found that tailwind was served from a cdn. A nice feature would be custom tailwind.config.js support. 

Instead of loading a remote static build for tailwind, we could just do what a normal tailwind install would do ([like this](https://tailwindcss.com/docs/guides/nextjs), but include tailwind as a dependency so the user doesn't have to do more. 

I was trying that out on my fork but was having problems.

**Comment by JcdeA** [comment]
Great!

I'll create a separate issue to track the tailwind.config.js support.
