### ISSUE TITLE
Firefox: No CSS

### ISSUE THREAD

**Issue by Gp2mv3** [LiveDuo/destack#23]
Hello,
I tried the project on Firefox (Ubuntu 21.04) and it seems like some CSS doesn't load when importing a module.
The dev console doesn't show any issue or error message except the favicon that 404.

![Screenshot from 2021-08-08 20-18-00](https://user-images.githubusercontent.com/1221806/128641729-02b68916-cda4-442f-864b-b114a6dbb104.png)

![Screenshot from 2021-08-08 20-16-27](https://user-images.githubusercontent.com/1221806/128641736-46876cf1-e357-46c8-8d16-7ca11ac366dd.png)

**Comment by LiveDuo** [comment]
Hey, thanks for the report.

It should be a CSS issue indeed. Will look further into it.

**Comment by LiveDuo** [comment]
@Gp2mv3 It's now fixed! To get it working update Destack to the latest version ie. `npm i destack@latest`.
