### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by StitiFatah** [LiveDuo/destack#29]
NextJS is under the MIT license, same for TailwindCSS, Grapesjs is under the BSD 3-Clause License but I don't seem to find the license for this particular project, haven't you decided yet ?

**Comment by LiveDuo** [comment]
@StitiFatah Not yet. Do you have a use case in mind where the license is a limit?

**Comment by StitiFatah** [comment]
I mean how should I know what I can/can't do with the software if it's not licensed ?

**Comment by vpckso** [comment]
Same question, can I use it for commercial?

**Comment by LiveDuo** [comment]
@StitiFatah The project is now under the MIT license. Thanks for bringing it to my attention.

**Comment by LiveDuo** [comment]
@vpckso Just updated the license. You can now use it with commercial projects freely.
