### ISSUE TITLE
This is such a beautiful project

### ISSUE THREAD

**Issue by beersweetpicklepanda** [LiveDuo/destack#31]
I really love this project. If I have all the necessary skills, I want to contribute. 
It's pretty simple for low-code dev like me who doesn't even understand how to modify html/css/js.

Not just a cute project, it has high potential to become open-source carrd, with adding more templates+marketplace, etc.

Is there a potential community in this project?

**Comment by LiveDuo** [comment]
Hey @beersweetpicklepanda.

That's exactly where the project is headed. When the time comes and the project is mature enough I will get in touch with designers and UI developers to build a marketplace for the project. There will be both free and paid themes but with the requirement that the theme is duplicated on the repository and developers can own their codebase. At that point Destack won't be limited to one theme and will be suitable for even more projects.

At the moment the current focus is on "Multi-page" support and bringing to life the "React" version of the project. Right after these two are delivered emphasis will be given to template support and growing the project!

**Comment by beersweetpicklepanda** [comment]
Thanks, @LiveDuo, for the roadmap!

I know growing this project and the community takes time. It makes me confident exploring it since you do have plans ahead.

I will commit to exploring this project!
