### ISSUE TITLE
Header Vector Swaps

### ISSUE THREAD

**Issue by cvoadmin** [LiveDuo/destack#35]
Firstly thanks for your efforts in putting this together. Making Tailblocks sites is a breeze. 
Just curious what's the correct way to swap the header component svg.
In [https://destack-page.vercel.app/](https://destack-page.vercel.app/), swapping the svg's ViewBox and Path (plain dimensions, no tags) doesn't seem to work across all the vectors I tried, leaving nothing but a solid background.

**Comment by LiveDuo** [comment]
Hey @cvoadmin,

There are two ways to change the header SVG:
1. Enter a new path in the component settings
2. Replace the who component with a new image component and then add an image of your choice.

If you stumbled across a bug, feel free to share the exact SVG path you entered or any other way to reproduce the problem.

**Comment by cvoadmin** [comment]
For reference, I tried vectors from SVGrepo.com  
After a bit of research I learned tailwind devs use [Hero Icons.](https://heroicons.com/) Something about the design eh...

**Comment by cvoadmin** [comment]
[Tabler Icons](https://tabler-icons.io/) is also great source. Maybe implementing these for quick swaps would be neat.
Closing for now.
