### ISSUE TITLE
Next js export doesn't get proper static builds

### ISSUE THREAD

**Issue by kaansey** [LiveDuo/destack#36]
Hey,  thanks for your effort to putting this together.
I just tried get static build with the [Next js example](https://github.com/LiveDuo/destack-starter).
In the index.html it only has some js & css files and the props (__NEXT_DATA__). It doesn't look like SEO friendly.

Is there any work around to get static build?
Screenshot from the sample project page source
![image](https://user-images.githubusercontent.com/2125613/147711082-841146aa-7114-447c-a20d-9be296de142f.png)

**Comment by LiveDuo** [comment]
Hey @kaansey,

The `static` build does not affect Next.js SEO features as far as I'm awair.

So you will have to just change the SEO elements as in any Next.js app.

For example, you can do the following:
```js
import 'grapesjs/dist/css/grapes.min.css'
export { getStaticProps } from 'destack/build/server'
import { ContentProvider } from 'destack'

import Head from 'next/head'

import image from 'path-to-the-cover-image'

function Page(props) { 
  return (
    <div style={{height: '100%'}}>
      <Head>
        <title>My page title</title>
        <meta name="image" content={image} />
        <meta property="og:image" content={image} />
        <meta name="twitter:card" content="summary_large_image"/>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <ContentProvider {...props}/>
    </div>
  )
}

export default Page

```

Note: To get the code above to work you will also need `next-images` installed in your project and set up in `next.config.js`.

**Comment by kaansey** [comment]
Thanks for your reply.
Actually I mean the page source is doesn't look good. 
For example if you have something like this

![image](https://user-images.githubusercontent.com/2125613/148263388-6ba0af5e-b37d-4af8-b502-80369b758aca.png)


When you got the export
```sh
yarn export
```
There is no dom element like  below in the `index.html`. It is only defined in the `<script id="__NEXT_DATA__" type="application/json">`
```html
<div> hello world </div>
```

What I expected is static html output like if you try to get export with `nextjs` sample project you can see the dom element in the `index.html`
![image](https://user-images.githubusercontent.com/2125613/148263892-6cc615a2-6dea-4d5e-8a08-2ed873d56ade.png)



I think it might be because of dynamic component usage on destack?

**Comment by JcdeA** [comment]
Yep, the elements are generated on-fly. Technically, it's not proper static builds, but it's the closest we can go afaik.

**Comment by LiveDuo** [comment]
Exactly. We are not aware of a way to pre-render dynamic HTML with Next.js so this is not available at the moment. If something comes up in the future we will look into it.
