### ISSUE TITLE
How to submit form?

### ISSUE THREAD

**Issue by apugoneappu** [LiveDuo/destack#37]
Hey there, 

Amazing project, thanks for all the great work! 

Just wanted to ask how to submit the form? I am running the [destack starter repo](https://github.com/LiveDuo/destack-starter) locally. 

I have 
- added a component with a form
- made a file [pages/api/submit.js](https://github.com/LiveDuo/destack/blob/main/dev/nextjs-project/pages/api/submit.js)
- selected the form and changed the component settings to:
  - Method: POST
  - Action: /api/submit
  - Async: ON (checked)
- selected the Button and set it to SUBMIT.

**Comment by LiveDuo** [comment]
Hi @apugoneappu,

Glad you liked Destack. Through your issue I realised I missed a bit of config in `pages/api/submit.js`

To get the form submission to work head back to [pages/api/submit.js](https://github.com/LiveDuo/destack/blob/main/dev/nextjs-project/pages/api/submit.js) to find the corrected api route.
