### ISSUE TITLE
How to edit <p> and table cell?

### ISSUE THREAD

**Issue by loongmxbt** [LiveDuo/destack#38]
Hi, this is really a great project. I've played with it today but can't find a way to edit some of the blocks inside. Such as <p> and table cell. I tried double click but it didn't change to edit mode like <text>. Also I can't find where to set the text in the right panel.
Could anyone give some help? Thanks a lot!

![image](https://user-images.githubusercontent.com/5986600/151366633-32bf5a03-43ae-42c0-b271-eb21e04ea841.png)
![image](https://user-images.githubusercontent.com/5986600/151366714-c246dfd8-0a9a-46e1-9b87-c3b55102631e.png)

**Comment by LiveDuo** [comment]
Hey @loongmxbt, that is indeed a bug. I've just pushed a fixed and bump the npm version so feel free to run `npm i destack@latest` and try it again.

**Comment by loongmxbt** [comment]
Thank you very much, I can edit the content!
