### ISSUE TITLE
componenst React?

### ISSUE THREAD

**Issue by vizardkill** [LiveDuo/destack#39]
Since the project uses grapes js, is it possible to build React components to add the editor within the project?

**Comment by LiveDuo** [comment]
@vizardkill 

If you want to use external react components in Destack's editor, that is not possible.

But, you can create a new Next.js page and your React components along Destack.

Eg.

```js
import { ContentProvider } from 'destack'
import 'grapesjs/dist/css/grapes.min.css'

export { getStaticProps } from 'destack/build/server'

export default function Page(props) { 
    return (
        <div style={{height: '100%'}}>
            <span>Hello world</span>
            <ContentProvider {...props}/>
        </div>)
}
```
