### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by UPDOWNUP-64BIT** [LiveDuo/destack#41]
I've followed the video and installed this package and build a nice little website but when i build and start the app the website is just white

I see the json file under `data` and my html is in there but its not loading any idea what i did wrong?

steps:
first i typed in term: `npm i destack`

second: `made a new path: pages/api/builder` and added a file called `handle.js` and added `export { handleData as default, config } from 'destack/build/server'`

third i added `import 'grapesjs/dist/css/grapes.min.css'
export { getStaticProps } from 'destack/build/server'
export { ContentProvider as default } from 'destack'` to my `index.js`

then i just designed my website ran npm run build then ran npm run start

**Comment by LiveDuo** [comment]
@UPDOWNUP-64BIT 

In general it seems good.

The instructions you followed are for Next.js and require Next.js to be already installed in your project. There are different instructions for React.

Also, might be worth comparing what you have with https://github.com/LiveDuo/destack-starter which shows the correct way to have Destack set up.

**Comment by santoni0** [comment]
I also wanted to use Destack in my new project. I set up a few items. run `npm run build` and `npm start` shows me only the white page. I use Next.js.

**Comment by beingArkReal** [comment]
@santoni0 did you pass showInProduction props?

cc @LiveDuo
