### ISSUE TITLE
creation of components in any pages  but No components display after refreshing any pages in nextjs

### ISSUE THREAD

**Issue by fvadouko** [LiveDuo/destack#48]
hey,

when i create  a page with these destack components, in nextjs then i refresh this page, the components disappear: there is a blank page. However, if i set up the index page with the components, in nextjs, then i will refresh the index page, it will contain all the previous components placed, in the index page.

Let's imagine, i create a page named "souffixe.js" in nextjs. Then i run it in the browser like 'http://localhost:3001/souffixe'. Then i place  the destack component like blog, in this page, then i refresh this page, all the components disappear. And i see "souffixe.json", in the files explorer, in the "data" folder.

How could you fix it? Or help me, fix it, please?

**Comment by man-pham** [comment]
I confirm the same issue happening for me.

**Comment by LiveDuo** [comment]
I missed this at the time. If someone encounters the same problem again, feel free to re-open the issue.
