### ISSUE TITLE
Doesn't save the layout for pages 

### ISSUE THREAD

**Issue by artemdzyuba** [LiveDuo/destack#50]
I was testing how to use the builder on the page other than index.js
So I created a page, let's say test.js, pasted this code onto it:
```
import 'grapesjs/dist/css/grapes.min.css'
export { getStaticProps } from 'destack/build/server'
export { ContentProvider as default } from 'destack'
```
Then I run `npm run dev` and open http://localhost:3000/test. The builder works, but doesn't save anything. So on refreshing or builing I get a blank page.

**Comment by man-pham** [comment]
Hi @LiveDuo ,
 Can you check the `${window.location.pathname}.json`  in the handleEvents  function. I think that `${window.location.pathname}.json` will be "/test.json" in this case.
 
 
`const handleEvents = (newEditor, standaloneServer): void => {
  const baseUrl = standaloneServer ? `http://localhost:${port}` : ''
  const path =
    window.location.pathname === '/' || window.location.pathname === ''
      ? 'default.json'
      : `${window.location.pathname}.json`
  const saveLocally = (data): Promise<JSON> =>
    fetchJSON({
      method: 'post',
      url: `${baseUrl}/api/builder/handle`,
      data: { path, data },
    })
  newEditor.on('storage:store', (e) => saveLocally(e))
}`

**Comment by man-pham** [comment]
Oh! I was wrong.
In the `loadTemplate` function. I think this line code 
`const pathNameWindows = location.pathname === '/' ? '\\default.json' : `${location.pathname}.json`
should be `const pathNameWindows = location.pathname === '/' ? '\\default.json' : `\\${location.pathname.substring(1)}.json`.
@LiveDuo Can you check about that?

**Comment by artemdzyuba** [comment]
@man-pham This thread is named "Doesn't save the layout for pages". Your messages are unrelated to the topic.
