### ISSUE TITLE
GrapesJS plugins/presets

### ISSUE THREAD

**Issue by GoodPHP** [LiveDuo/destack#53]
Hi guys,

I want to show you my features for grapesjs:
https://gjs.market/authors/devfuture-development

**Comment by LiveDuo** [comment]
Hey @GoodPHP,

Feel free to include Destack in the "Site Builder" section.

**Comment by GoodPHP** [comment]
Hi @LiveDuo ,

Soon, there be possible to publish any developers features. I'll ping you to publish your product.

**Comment by GoodPHP** [comment]
Hey @LiveDuo ,
There are service for developers:
https://my.gjs.market/login
