### ISSUE TITLE
The multiple pages feature not working correctly.

### ISSUE THREAD

**Issue by man-pham** [LiveDuo/destack#56]
Hi,
I have created a new page (blog.js) and setup destack. But i don't see any sections which has been added in the page after I reload the page. 
And my source code still have "data/blog.json" file. But I don't know why it's not showing up on the "blog" page. 

So I think the cause of this error in the [loadTemplate](https://github.com/LiveDuo/destack/blob/main/lib/destack/src/components/initEditor.tsx) function. Please check!

P/S: Run the project in development `npm run dev`

**Environment**
- "destack": "1.0.3"
- "next": "13.0.2"
- "grapesjs": "0.20.1"
- "react": "18.2.0"
- node v16.13.2
- OS Windows 11

**Comment by Omar8345** [comment]
Got some issue!

**Comment by LiveDuo** [comment]
@man-pham @Omar8345 

It's hard for me to check directly (don't have access to a Windows 11 machine atm).

It would be helpful if you share the error logs from the Developers' Console.

**Comment by Omar8345** [comment]
Hi sure.

**Comment by Omar8345** [comment]
There is no errors in console of browser neither terminal

**Comment by Omar8345** [comment]
i will use my raspberry pi or WSL

**Comment by Omar8345** [comment]
I have tested it on WSL and Raspberry Pi it's all good, but I still don't have an idea about the issue

**Comment by LiveDuo** [comment]
@Omar8345 One more thing to check is the Network tab and see if the `api/builder/handle` endpoint fails at any point in the process
