### ISSUE TITLE
How to use grapesjs-export plugin

### ISSUE THREAD

**Issue by rainerregan** [LiveDuo/destack#69]
Hi, thanks for this amazing project. I need to use this project along with GrapesJs export plugin. how can I do that?

**Comment by LiveDuo** [comment]
@rainerregan Glad you like it.

It's not possible at the moment and the project is moving in a different direction. See #62 for more info.

What you can do:
1) Create the exported zip file from the created json files in the `data` folder without directly using the export plugin.
2) Fork Destack and enable support for the plugin yourself.
