### ISSUE TITLE
Cannot contribute on fresh clone 

### ISSUE THREAD

**Issue by kronos-999** [LiveDuo/destack#75]
I followeed the exact instructions for contributing, but when I run "npm run dev", I get the following:
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
[0] client/craft/index.tsx (16:4)
[0] 14: const ContentProviderBase: React.FC<ContentProviderBaseProps> = ({ data, standaloneServer }) => {
[0] 15:   return (
[0] 16:     <ThemeProvider>
[0]         ^
[0] 17:       <div className="h-full h-screen">
[0] 18:         <Editor data={data} standaloneServer={standaloneServer} />

Also, I get the following on the server afterwards:

 bundles server/index.ts → build/server...
[0] created build/server in 4s
[1] node:internal/crypto/hash:71
[1]   this[kHandle] = new _Hash(algorithm, xofLen);
[1]                   ^
[1] 
[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:71:19)
[1]     at Object.createHash (node:crypto:140:10)

**Comment by LiveDuo** [comment]
It seems there could be something broken with imports. It works on my system atm but I'll be trying a clean install in a bit to verify.

There's also a failing build that I missed https://github.com/LiveDuo/destack/actions/runs/4317946271/jobs/7535646291.

**Comment by LiveDuo** [comment]
@kronos-999 Update: After a clean install I get the error the first time. Then after running the command again the error goes away.

What seems to happen:
- The Next.js example project needs the Destack editor CSS to function
- The CSS is dynamically generated with rollup and the tailwindcss plugin and does not exists at first
- The example project the first time it started could not found the CSS and throws that error

**Comment by LiveDuo** [comment]
@kronos-999 In the `master` branch the `ArrowUpTrayIcon` looks commented out [Header.tsx#L73](https://github.com/LiveDuo/destack/blob/main/lib/client/craft/viewport/Header.tsx#L73), if you see an error something maybe rollup is ignoring the comments or you checked out on a different branch. Lmk whether the case to look it up.

When you run `npm run dev` twice it should compile. That's with either npm or nnpm (I haven't tested pnpm though), at least on my machine it does, the first time fails to load the CSS and the second it compiles sucessfully.

**Comment by LiveDuo** [comment]
It seems that the example projects that are used for dev are not importing `destack` correctly.

Looking into them I noticed that `destack` is not imported at all in their `package.json` files. This I guess depends on how npm workspaces work and I'd like to look into it somehow but I can't reproduce it on my machine.

Maybe if destack is imported in the example projects it will work.

ie. in [./dev/nextjs-project/package.json](https://github.com/LiveDuo/destack/blob/main/dev/nextjs-project/package.json)
```diff
"dependencies": {
+    "destack": "file:../../lib/",
    "next": "^10.2.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
```

**Comment by LiveDuo** [comment]
Hey @kronos-999,

Glad that it works now. We spend quite some time ironing out bugs over the last few weeks.

I've reproduced the issue locally. For more context, I was aware that something was off with [text-transparent](https://tailwind.build/classes/text-color/text-transparent) Tailwind class but didn't notice that component.

Maybe create another Github issue specifically for this bug?
