### ISSUE TITLE
Preview mode discards last change

### ISSUE THREAD

**Issue by sergeylukin** [LiveDuo/destack#78]
Bug appears after commit 37c0403

Steps to reproduce:

- Add block
   
    <img width="745" alt="Screen Shot 2023-06-05 at 20 09 50" src="https://github.com/LiveDuo/destack/assets/720339/5b115f7e-311e-4945-a645-101e5b6f65e5">

- Edit text

    <img width="747" alt="Screen Shot 2023-06-05 at 20 09 58" src="https://github.com/LiveDuo/destack/assets/720339/8cf18e4d-f367-42b9-8c38-be099f1638f2">

- Switch to Preview mode - *change does not appear*

    <img width="749" alt="Screen Shot 2023-06-05 at 20 10 42" src="https://github.com/LiveDuo/destack/assets/720339/a77070f6-cfff-4979-af63-787834a62048">

**Comment by LiveDuo** [comment]
Thanks for reporting. I managed to reproduced it locally.

Next week I'd be working on Destack and put fixing this on the list of stuff to do.

**Comment by LiveDuo** [comment]
Just pushed a fix https://github.com/LiveDuo/destack/commit/ccbc66aead784a1b6ef65582ea9ebe368754d857.

**Comment by sergeylukin** [comment]
Amazing! Works like a charm 🥇

**Comment by LiveDuo** [comment]
@sergeylukin Awesome!
