### ISSUE TITLE
path undefined error

### ISSUE THREAD

**Issue by chandranfullstack** [LiveDuo/destack#89]
Unhandled Runtime Error
TypeError: Path must be a string. Received undefined

Call Stack
assertPath
node_modules\next\dist\compiled\path-browserify\index.js (1:95)
Object.parse
node_modules\next\dist\compiled\path-browserify\index.js (1:4265)
eval
node_modules\destack\build\server\index.js (1886:0)
(app-client)/./node_modules/destack/build/server/index.js
file:///C:/Users/ravic/Desktop/Flugid/nextbuilder/.next/static/chunks/app/page.js (105:1)
options.factory
/_next/static/chunks/webpack.js (704:31)
__webpack_require__
file:///C:/Users/ravic/Desktop/Flugid/nextbuilder/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (359:21)
eval
webpack-internal:///(app-client)/./src/app/page.js (7:78)
(app-client)/./src/app/page.js
file:///C:/Users/ravic/Desktop/Flugid/nextbuilder/.next/static/chunks/app/page.js (159:1)
options.factory
/_next/static/chunks/webpack.js (704:31)
__webpack_require__
file:///C:/Users/ravic/Desktop/Flugid/nextbuilder/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (359:21)
Next.js
requireModule
node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (144:0)
initializeModuleChunk
node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (1205:0)
resolveModuleChunk
node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (1163:0)
eval
node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (1590:0)

**Comment by LiveDuo** [comment]
@chandranfullstack There's not enough information to reproduce the issue. Please share a repo or more info to reproduce or try upgrading the the latest version.

Does it work with the starter projects such as [destack-starter](https://github.com/LiveDuo/destack-starter)?

**Comment by chandranfullstack** [comment]
Thank You for your reply I solved the error  I did't expect your reply
