### ISSUE TITLE
Tailwind .text-transparent 

### ISSUE THREAD

**Issue by kronos-999** [LiveDuo/destack#93]
Hello,
Upon request I am opening a new issue to explain that on a fresh clone there are some discrepancies with how the UI looks. I explained it to @LiveDuo here: #75 

Where could the issue be?

**Comment by LiveDuo** [comment]
I noticed the class `.bg-clip-text` was missing `-webkit-background-clip: text;` in the editor compared to a fresh tailwind project. With some more research I stumbled upon https://tailwindcss.com/docs/browser-support#vendor-prefixes which explains what is going on.

Pushed a fix with https://github.com/LiveDuo/destack/commit/c98da786c661c106aa4f7147a56672d3df4a170b. Will release a hotfix at some point next week for the NPM version.
