### ISSUE TITLE
Enable custom HTML markup

### ISSUE THREAD

**Issue by kronos-999** [LiveDuo/destack#94]
Hello, since we are trying to become a better shuffle.dev, I was thinking of a couple ideas. One of them (among importing markup from cdn servers to enable truly custom code to enter) was to have a live HTML Editor for the markup. A smal JS editor on the side could also be a possibility

**Comment by LiveDuo** [comment]
Hey @kronos-999, 

That's an idea that I have long toy with and is requested in various forms from many community members:
1. [How to add another component #55](https://github.com/LiveDuo/destack/issues/55)
2. [Custom components #1](https://github.com/LiveDuo/destack/issues/1)
3. [React components #72](https://github.com/LiveDuo/destack/discussions/72)

I think custom HTML components is the more simple option.
- These components need to be stored somewhere in the user' repository so they are persistent across refreshes (maybe in the `data` folder).
- The HTML components won't have a preview image as that is not generated on the fly

A custom HTML editor is also not close to what we have. The Craft.js version uses react and stores the components in a json file. That means that during development, there is no HTML to edit. That's different from the Grapes.js version - which if you haven't already might be worth giving a try.

**Comment by LiveDuo** [comment]
@kronos-999  Version 3 is out now and it's now easy to edit the component HTML. You can either edit it in your browser DevTools or edit the template file directly that now uses HTML.
