### ISSUE TITLE
Nextjs build can't show the page

### ISSUE THREAD

**Issue by Cobb-Zhang** [LiveDuo/destack#97]
Nextjs version:  13.4.19
destack version: 2.1.2
issue: 
when I build the project and start it, the page can't show the page that i create in the dev environment.
![image](https://github.com/LiveDuo/destack/assets/71749951/e73306ea-2cbc-4c0e-9647-1942eb99ae1c)

**Comment by franciscoarruda** [comment]
Having the same problem, i believe is not finding the theme

**Comment by LiveDuo** [comment]
@Cobb-Zhang @franciscoarruda  I had a look on the issue.

From the screenshot it seemed there was an unnecessary request to the development server. I just pushed a fix for that  https://github.com/LiveDuo/destack/commit/565b886bfa105bad9458dc4033235489fead20fe.

I suggest you update to destack `2.1.3` and start your project again. If the problem persists I would need more info to figure it out. Maybe a repo that reproduces the problem and more details about your OS and the node/npm versions you are using.

**Comment by franciscoarruda** [comment]
I'm using Destack-Starter.

I tried again from the start:
- Downloaded Zip
- Installed dependencies (npm)
- Run build
- Run start

The error that shows is:
![error](https://github.com/LiveDuo/destack/assets/14877038/4750d36f-e3a7-4421-ac8f-23edb990a11c)
![error2](https://github.com/LiveDuo/destack/assets/14877038/24a2f7d3-58a6-4bb9-bc7e-a24533349a22)

**Comment by franciscoarruda** [comment]
Yes i did run build and the run start

**Comment by franciscoarruda** [comment]
I believe the error comes from this function, not sure

![error3](https://github.com/LiveDuo/destack/assets/14877038/9120041e-267e-426a-8665-5c79f1a06d36)

**Comment by LiveDuo** [comment]
It should do. Although I don't get the error, I noticed that when I delete `data/default.json` then this exact issue appears.

**Comment by LiveDuo** [comment]
@franciscoarruda It was an issue with Windows that had some differences from unix based systems such as Mac and Linux.

Should be fixed by https://github.com/LiveDuo/destack/commit/eb7ba180794b449223b7cc46f28c5d4edcdb632e and https://github.com/LiveDuo/destack/commit/506ed94c9a1a3479a5de1607987431076631728f.

I tested it on a Windows machine and it works fine. If you still experience issues let me know.

**Comment by franciscoarruda** [comment]
Fixed 👌🫡
Nice project btw !

**Comment by LiveDuo** [comment]
Thanks!

**Comment by Cobb-Zhang** [comment]
@LiveDuo  Fixed，good job ！This project is really convenient！

**Comment by Cobb-Zhang** [comment]
Just as you say, update the lastest version which can fix the problem.
