### ISSUE TITLE
Editor standalone use

### ISSUE THREAD

**Issue by PatrickMA** [LiveDuo/destack#98]
Hello,

Is it possible to use the (craft) Editor and the full-preview of the components as a standalone components where i can pass the JSON? 

Thank you!

**Comment by LiveDuo** [comment]
@PatrickMA Hey, if you are willing to mess a little with the source code it's not too hard. You'd need to change the  [Editor.tsx](https://github.com/LiveDuo/destack/blob/main/lib/client/craft/editor/Editor.tsx#L23) so it uses a custom JSON that should be passed to `actions.deserialize`.

**Comment by PatrickMA** [comment]
@LiveDuo Thank you very much!
