### ISSUE TITLE
Destack Not working for latest Next.js 

### ISSUE THREAD

**Issue by umashankar-pardhi-amla** [LiveDuo/destack#99]
Hi Team,

This plugin is not working for the latest next.js 

![image](https://github.com/LiveDuo/destack/assets/79130351/74a9456d-66ba-46de-989c-c9f6e50953ec)

**Comment by LiveDuo** [comment]
Hey @umashankar-pardhi-amla, the Destack [destack starter](https://github.com/LiveDuo/destack-starter) project has the latest stable version of Next.js. Have you tried that one out?

**Comment by umashankar-pardhi-amla** [comment]
Hi @LiveDuo 

Thanks for directing me to the right path.

Is it possible to use my existing components available next.js or a new way of creating component that I can use for page builder? Or How to use the script.

**Comment by LiveDuo** [comment]
> Is it possible to use my existing components available next.js or a new way of creating component that I can use for page builder? 

Right now it's hard to use with other components. In the future you will be able to import custom components but that's not available right now.

> Or How to use the script.

See https://github.com/LiveDuo/destack#getting-started for more details.

**Comment by umashankar-pardhi-amla** [comment]
Is there any example, because it does not make sense to generate HTML and things hardcoded? Components will bind with data so it will be helpful. Do you have any example with the component.

**Comment by LiveDuo** [comment]
@umashankar-pardhi-amla It surely be beneficial no doubt.
